In [38]:
# 미국 Boston 지역의 집값 data 불러오기
import pandas as pd
house = pd.read_csv('https://raw.githubusercontent.com/rasbt/'
    'python-machine-learning-book-2nd-edition'
    '/master/code/ch10/housing.data.txt', header=None, sep='\s+')
house.columns = ['CRIM', 'ZN', 'INDUS', 'CHAS', 'NOX', 'RM', 'AGE',
                 'DIS', 'RAD', 'TAX', 'PTRATIO', 'B', 'LSTAT', 'MEDV']
house.head()

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  \
0  0.00632  18.0   2.31     0  0.538  6.575  65.2  4.0900    1  296.0   
1  0.02731   0.0   7.07     0  0.469  6.421  78.9  4.9671    2  242.0   
2  0.02729   0.0   7.07     0  0.469  7.185  61.1  4.9671    2  242.0   
3  0.03237   0.0   2.18     0  0.458  6.998  45.8  6.0622    3  222.0   
4  0.06905   0.0   2.18     0  0.458  7.147  54.2  6.0622    3  222.0   

   PTRATIO       B  LSTAT  MEDV  
0     15.3  396.90   4.98  24.0  
1     17.8  396.90   9.14  21.6  
2     17.8  392.83   4.03  34.7  
3     18.7  394.63   2.94  33.4  
4     18.7  396.90   5.33  36.2

In [39]:
# 종속변수 MEDV(집가격)와 설명변수의 Plot 그리기.
import plotly.express as px
fig = px.scatter_matrix(house,
    dimensions=['LSTAT', 'INDUS', 'NOX', 'RM', 'MEDV'],
    title='Scatter Matrix')
fig.show()
fig = px.scatter_matrix(house,
    dimensions=['ZN', 'AGE', 'DIS', 'TAX', 'PTRATIO', 'MEDV'],
    title='Scatter Matrix')
fig.show()

In [40]:
# 종속변수 MEDV(집가격)와 설명변수의 상관계수 행렬 구하기
import numpy as  np
col1=['LSTAT', 'INDUS', 'NOX', 'RM', 'MEDV']
col2=['ZN', 'AGE', 'DIS', 'TAX', 'PTRATIO', 'MEDV']
a=house[col1].values
print(a.shape)
cm1 = np.corrcoef(house[col1].values.T)
cm2 = np.corrcoef(house[col2].values.T)
print(cm1)
print(cm2)

(506, 5)
[[ 1.          0.60379972  0.59087892 -0.61380827 -0.73766273]
 [ 0.60379972  1.          0.76365145 -0.39167585 -0.48372516]
 [ 0.59087892  0.76365145  1.         -0.30218819 -0.42732077]
 [-0.61380827 -0.39167585 -0.30218819  1.          0.69535995]
 [-0.73766273 -0.48372516 -0.42732077  0.69535995  1.        ]]
[[ 1.         -0.56953734  0.66440822 -0.31456332 -0.39167855  0.36044534]
 [-0.56953734  1.         -0.74788054  0.50645559  0.26151501 -0.37695457]
 [ 0.66440822 -0.74788054  1.         -0.53443158 -0.23247054  0.24992873]
 [-0.31456332  0.50645559 -0.53443158  1.          0.46085304 -0.46853593]
 [-0.39167855  0.26151501 -0.23247054  0.46085304  1.         -0.50778669]
 [ 0.36044534 -0.37695457  0.24992873 -0.46853593 -0.50778669  1.        ]]


In [41]:
# 일부 변수에 대한 log 변환
import numpy as np
house['LLSTAT']=np.log(house['LSTAT'])
house['LINDUS']=np.log(house['INDUS'])
house.head()

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  \
0  0.00632  18.0   2.31     0  0.538  6.575  65.2  4.0900    1  296.0   
1  0.02731   0.0   7.07     0  0.469  6.421  78.9  4.9671    2  242.0   
2  0.02729   0.0   7.07     0  0.469  7.185  61.1  4.9671    2  242.0   
3  0.03237   0.0   2.18     0  0.458  6.998  45.8  6.0622    3  222.0   
4  0.06905   0.0   2.18     0  0.458  7.147  54.2  6.0622    3  222.0   

   PTRATIO       B  LSTAT  MEDV    LLSTAT    LINDUS  
0     15.3  396.90   4.98  24.0  1.605430  0.837248  
1     17.8  396.90   9.14  21.6  2.212660  1.955860  
2     17.8  392.83   4.03  34.7  1.393766  1.955860  
3     18.7  394.63   2.94  33.4  1.078410  0.779325  
4     18.7  396.90   5.33  36.2  1.673351  0.779325

In [42]:
# 전체 data를 종속변수 y와 특성변수 X의 data로 나누기
y = house['MEDV'].values
house1=house.drop(['LSTAT', 'INDUS', 'MEDV'], axis=1)
X = house1.values

In [43]:
# 전체 data를 training data(70%)와 test data(30%)로 나누기
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y,
    test_size=0.3, random_state=1)

In [44]:
# regression module 불러오기와 모형추정
from sklearn.linear_model import LinearRegression
mlr = LinearRegression()
mlr.fit(X_train, y_train)

LinearRegression()

In [45]:
# 추정값 확인
print('Slpoe:', mlr.coef_)
print('Intercept:' , mlr.intercept_)

Slpoe: [-1.36676828e-01  3.13177997e-02  2.52393199e+00 -1.70295629e+01
  1.23977704e+00  3.06818458e-02 -1.28840466e+00  2.61968148e-01
 -6.58141653e-03 -8.27862485e-01  4.90558897e-03 -9.97211822e+00
 -6.04522425e-01]
Intercept: 65.69779117501746


In [46]:
# 예측치 구하기
y_train_pred = mlr.predict(X_train)
y_test_pred = mlr.predict(X_test)

In [47]:
# 잔차에 대한 plot 그리기.
import plotly.graph_objects as go
fig=go.Figure()
fig.add_trace(go.Scatter(x=y_train_pred, y=y_train_pred-y_train,
    mode='markers', name='Training data'))
fig.add_trace(go.Scatter(x=y_test_pred, y=y_test_pred-y_test,
    mode='markers', name='Test data'))
fig.update_layout(width=600, height=400,
    title_text='Residual Plots versus predicted values', title_x=0.5)
fig.update_xaxes(title_text='predicted')
fig.update_yaxes(title_text='residuals')
fig.show()

In [48]:
# 모형의 MSE
from sklearn.metrics import mean_squared_error
print('MSE train: %.3f, test: %.3f' %
    (mean_squared_error(y_train, y_train_pred),
    mean_squared_error(y_test, y_test_pred)))

MSE train: 18.139, test: 17.416


In [49]:
# 모형의 R^2
from sklearn.metrics import r2_score
print('R^2 train: %.3f, test: %.3f' %
    (r2_score(y_train, y_train_pred),
    r2_score(y_test, y_test_pred)))

R^2 train: 0.777, test: 0.810


In [50]:
########### 로버스트 회귀 'RANSAC Regressor'
from sklearn.linear_model import RANSACRegressor
rans = RANSACRegressor(max_trials=100, min_samples=45,
    loss='absolute_error', residual_threshold=5.0, random_state=1)
rans.fit(X_train, y_train)
y_train_pred=rans.predict(X_train)
y_test_pred=rans.predict(X_test)
print(rans.estimator_.coef_)
print(rans.estimator_.intercept_)


[-0.33997467  0.02628575  1.26584351 -6.7774809   3.20459419 -0.03651634
 -1.13372086  0.24298439 -0.00712198 -0.59996172  0.01186441 -3.85624577
 -1.01175348]
31.427983601251164


In [51]:
# 모형의 MSE training set
mean_squared_error(y_train, y_train_pred)

26.959180677416427

In [52]:
# 모형의 MSE test set
mean_squared_error(y_test, y_test_pred)

22.296199901347684

In [53]:
# RANSAC에서 회귀 계수를 추정하는데 사용한 데이터(inner)와
# 특이치(outlier) 출력
inlier_mask=rans.inlier_mask_
print('inner', inlier_mask)

inner [ True  True False  True False  True  True  True False False  True  True
  True  True  True  True  True  True  True False  True  True  True  True
  True  True False  True  True  True  True  True  True  True  True False
  True  True  True  True  True  True False  True False  True False False
  True False  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True False  True  True  True  True  True  True  True False  True
  True False False  True  True  True  True False  True  True  True  True
  True  True  True  True  True  True  True  True  True False  True  True
  True  True False  True  True False False  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True False  True  True  True False
  True  True  True  True  True False  True  True  True  True False  True
  True  True  True  True  True  True  True  T

In [54]:
outlier_mask=np.logical_not(inlier_mask)
print('outlier', outlier_mask)

outlier [False False  True False  True False False False  True  True False False
 False False False False False False False  True False False False False
 False False  True False False False False False False False False  True
 False False False False False False  True False  True False  True  True
 False  True False False False False False False False False False False
 False False False False False False False False False False False False
 False False  True False False False False False False False  True False
 False  True  True False False False False  True False False False False
 False False False False False False False False False  True False False
 False False  True False False  True  True False False False False False
 False False False False False False False False False False False False
 False False False False False False False  True False False False  True
 False False False False False  True False False False False  True False
 False False False False False False False 

In [55]:
############# SVR.Regression......
from sklearn.svm import SVR # SVR module import
svl=SVR(kernel = 'linear', C=1.0, epsilon=0.1) # 선형 SVM회귀
svr=SVR(kernel = 'rbf', C=1.0, epsilon=0.1) # 비선형 SVM회귀
svl.fit(X_train, y_train)
svr.fit(X_train, y_train)

SVR()

In [56]:
print(svl.support_)
print(svl.coef_)
print(svl.intercept_)

[  1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
  19  20  21  22  23  24  25  26  28  29  30  31  32  33  34  35  36  37
  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53  54  55
  56  58  59  60  61  62  63  64  65  66  67  68  70  71  72  73  74  75
  76  77  78  79  80  81  82  83  84  85  86  87  88  89  90  91  92  93
  94  95  96  97  98  99 100 101 102 103 104 105 106 107 108 109 110 111
 112 113 114 115 116 117 118 119 120 121 122 123 124 125 126 127 128 129
 130 131 132 133 135 136 137 138 139 140 141 142 143 144 145 147 148 149
 150 151 152 153 154 155 156 157 158 159 160 161 162 163 164 165 166 167
 168 169 170 171 172 173 174 175 176 177 179 180 181 182 183 184 185 186
 187 188 189 190 191 192 193 194 195 196 197 198 199 200 201 202 203 204
 205 206 207 208 209 210 211 212 213 214 215 216 217 218 219 220 221 222
 223 224 225 226 227 228 229 231 232 233 234 235 236 237 238 239 240 241
 242 243 244 245 246 247 248 249 250 251 253 254 25

In [57]:
# SVM 회귀 예측치 계산
y_train_predsvl=svl.predict(X_train)
y_train_predsvr=svr.predict(X_train)
y_test_predsvl=svl.predict(X_test)
y_test_predsvr=svr.predict(X_test)

In [58]:
# 모형의 MSE
from sklearn.metrics import mean_squared_error
mse_l_trina=mean_squared_error(y_train, y_train_predsvl)
mse_l_test=mean_squared_error(y_test, y_test_predsvl)
mse_n_train=mean_squared_error(y_train, y_train_predsvr)
mse_n_test=mean_squared_error(y_test, y_test_predsvr)
print(mse_l_trina, mse_l_test, mse_n_train, mse_n_test)

22.269660619198177 16.382173270965822 66.44380086215857 75.25569380095274


In [59]:
# 모형의 R^2
from sklearn.metrics import r2_score
R2_l=r2_score(y_train, y_train_predsvl)
R2_n=r2_score(y_train, y_train_predsvr)
print(R2_l, R2_n)

0.7257061514413159 0.1816163630425146
