In [2]:
# 범주형 자료
x=[{'city':'seoul','temp':10.0},
   {'city':'Dubai','temp':33.5},
   {'city':'LA','temp':20.0}]
x

[{'city': 'seoul', 'temp': 10.0},
 {'city': 'Dubai', 'temp': 33.5},
 {'city': 'LA', 'temp': 20.0}]

In [4]:
from sklearn.feature_extraction import DictVectorizer
vec=DictVectorizer(sparse=False)
vec.fit_transform(x) # X를 범주형 수량화 자료로 변환

array([[ 0. ,  0. ,  1. , 10. ],
       [ 1. ,  0. ,  0. , 33.5],
       [ 0. ,  1. ,  0. , 20. ]])

In [6]:
# 메로리를 줄이기 위해 sparse=True
vec1=DictVectorizer(sparse=True)
x1=vec1.fit_transform(x)
x1

<3x4 sparse matrix of type '<class 'numpy.float64'>'
	with 6 stored elements in Compressed Sparse Row format>

In [8]:
x2=x1.toarray() # sparse=True를 풀고 배열로 변경
print(x1)
print(x2)
vec1.get_feature_names()

  (0, 2)	1.0
  (0, 3)	10.0
  (1, 0)	1.0
  (1, 3)	33.5
  (2, 1)	1.0
  (2, 3)	20.0
[[ 0.   0.   1.  10. ]
 [ 1.   0.   0.  33.5]
 [ 0.   1.   0.  20. ]]


['city=Dubai', 'city=LA', 'city=seoul', 'temp']

In [10]:
#텍스트 자료
text=['떴다 떴다 비행기 날아라 날아라',
      '높이 높이 날아라 우리 비행기',
      '내가 만든 비행기 날아라 날아라',
      '멀리 멀리 날아라 우리 비행기']
text

['떴다 떴다 비행기 날아라 날아라',
 '높이 높이 날아라 우리 비행기',
 '내가 만든 비행기 날아라 날아라',
 '멀리 멀리 날아라 우리 비행기']

In [12]:
from sklearn.feature_extraction.text import CountVectorizer
vec2 = CountVectorizer() #default는 sparse=True
# sparse=True를 풀고 text를 수량화 배열 자료로 변환
t=vec2.fit_transform(text).toarray()
import pandas as pd
t1=pd.DataFrame(t, columns=vec2.get_feature_names())
t1

c:\Users\user\anaconda3\lib\site-packages\sklearn\utils\deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)


날아라  내가  높이  떴다  만든  멀리  비행기  우리
0    2   0   0   2   0   0    1   0
1    1   0   2   0   0   0    1   1
2    2   1   0   0   1   0    1   0
3    1   0   0   0   0   2    1   1

In [14]:
from sklearn.feature_extraction.text import TfidfVectorizer
tfid=TfidfVectorizer()
# 높은 빈도는 낮은 가중치, 낮은 빈도는 높은 가중치
x2=tfid.fit_transform(text).toarray()
x3=pd.DataFrame(x2, columns=tfid.get_feature_names())
x3

c:\Users\user\anaconda3\lib\site-packages\sklearn\utils\deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)


날아라        내가       높이       떴다        만든       멀리       비행기        우리
0  0.450735  0.000000  0.00000  0.86374  0.000000  0.00000  0.225368  0.000000
1  0.229589  0.000000  0.87992  0.00000  0.000000  0.00000  0.229589  0.346869
2  0.569241  0.545415  0.00000  0.00000  0.545415  0.00000  0.284620  0.000000
3  0.229589  0.000000  0.00000  0.00000  0.000000  0.87992  0.229589  0.346869

In [16]:
# Polynomial 특성변수 생성
import plotly.express as px
import numpy as np
X=np.array([1,2,3,4,5])
Y=np.array([5,3,1,5,8])
fig=px.line(x=X,y=Y) # 선형회귀를 하기에는 부적합
fig.update_layout(width=500, height=380)
fig.show()

In [18]:
from sklearn.preprocessing import PolynomialFeatures
# include_bias는 절편항 여부
fg=PolynomialFeatures(degree=3, include_bias=True)
x1=fg.fit_transform(X[:,np.newaxis]) # 3차까지 생성
print(x1)

[[  1.   1.   1.   1.]
 [  1.   2.   4.   8.]
 [  1.   3.   9.  27.]
 [  1.   4.  16.  64.]
 [  1.   5.  25. 125.]]


In [19]:
from sklearn.linear_model import LinearRegression
import plotly.graph_objects as go
reg=LinearRegression()
reg.fit(x1, Y)
yfit=reg.predict(x1) #적합값
fig=go.Figure()
fig.add_trace(go.Scatter(x=X,y=Y,mode='lines',name='origin'))
fig.add_trace(go.Scatter(x=X,y=Y,mode='lines+markers', name='fitted'))
fig.show()