In [2]:
# 데이터 불러오기
import seaborn as sns
import numpy as np
# iris라는 변수명으로 Iris data를 download
iris = sns.load_dataset('iris')
print(iris.head())
# 'species'열을 drop하고 input X를 정의
X = iris.drop('species', axis=1)
y = iris['species']
print(np.unique(y))

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa
['setosa' 'versicolor' 'virginica']


In [3]:
# y data를 범주형으로 변환
import numpy as np
from sklearn.preprocessing import LabelEncoder
classle = LabelEncoder()
# species 열의 문자열을 categorical 값으로 전환
y = classle.fit_transform(iris['species'].values)
print(np.unique(y))

[0 1 2]


In [4]:
# 전체 data를 training set과 test set으로 split
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y,
                                                    test_size=0.3,
                                                    random_state=1,stratify=y)

In [5]:
# 표준화
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
sc.fit(X_train)
X_train_std = sc.transform(X_train)
X_test_std = sc.transform(X_test)

In [6]:
# Logistic regression
from sklearn.linear_model import LogisticRegression
# C = 1/⋋. 디폴트: L2, auto(One-versus-Rest-'ovr').
Logit = LogisticRegression(C=1e2, multi_class='ovr',random_state=1)
l_1=Logit.fit(X_train_std, y_train)
y_train_pred = Logit.predict(X_train_std)
y_test_pred = Logit.predict(X_test_std)

In [7]:
# Accuracy score
from sklearn.metrics import accuracy_score
print(accuracy_score(y_test,y_test_pred))
print(accuracy_score(y_train,y_train_pred))

0.9777777777777777
0.9428571428571428


In [8]:
# Confusion matrix
from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_test, y_test_pred))

[[15  0  0]
 [ 0 15  0]
 [ 0  1 14]]


In [10]:
from sklearn.linear_model import LogisticRegression
# C = 1/⋋. 디폴트: L2, max_iter=200
Logit = LogisticRegression(C=1e2, random_state=1, max_iter=200)
Logit.fit(X_train, y_train)
y_train_pred = Logit.predict(X_train)
y_test_pred = Logit.predict(X_test)
y_test_pred_proba=Logit.predict_proba(X_test)
print(y_test_pred[:5])
print(y_test_pred_proba[:5])

[2 0 0 2 1]
[[5.92938216e-10 5.81603829e-04 9.99418396e-01]
 [9.98974993e-01 1.02500667e-03 1.89351519e-20]
 [9.99810530e-01 1.89470231e-04 3.15252015e-21]
 [3.24057699e-05 4.39474580e-01 5.60493014e-01]
 [2.00491040e-05 9.99316752e-01 6.63199116e-04]]


In [11]:
from sklearn.metrics import accuracy_score
print(accuracy_score(y_test,y_test_pred))
print(accuracy_score(y_train,y_train_pred))
from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_test,y_test_pred))

1.0
0.9809523809523809
[[15  0  0]
 [ 0 15  0]
 [ 0  0 15]]


In [12]:
import joblib
joblib.dump(Logit,'./save.pkl')
logit_from_joblib=joblib.load('./save.pkl')
logit_pred=logit_from_joblib.predict(X_test)
print(accuracy_score(y_test, logit_pred))
print(confusion_matrix(y_test, logit_pred))
print(logit_pred)

1.0
[[15  0  0]
 [ 0 15  0]
 [ 0  0 15]]
[2 0 0 2 1 1 2 1 2 0 0 2 0 1 0 1 2 1 1 2 2 0 1 2 1 1 1 2 0 2 0 0 1 1 2 2 0
 0 0 1 2 2 1 0 0]
