In [3]:
#1
from sklearn.feature_extraction import DictVectorizer
x = [{'city' : 'Daegu','temp':12},
     {'city' : 'Seoul','temp':10},
     {'city' : 'Busan','temp':15},
     {'city' : 'Incheon','temp':9}]
vec = DictVectorizer(sparse=False)
x1 = vec.fit_transform(x)
vec = DictVectorizer(sparse=True)
x2 = vec.fit_transform(x)
print(x1)
print(x2)
print(vec.get_feature_names())

[[ 0.  1.  0.  0. 12.]
 [ 0.  0.  0.  1. 10.]
 [ 1.  0.  0.  0. 15.]
 [ 0.  0.  1.  0.  9.]]
  (0, 1)	1.0
  (0, 4)	12.0
  (1, 3)	1.0
  (1, 4)	10.0
  (2, 0)	1.0
  (2, 4)	15.0
  (3, 2)	1.0
  (3, 4)	9.0
['city=Busan', 'city=Daegu', 'city=Incheon', 'city=Seoul', 'temp']


In [18]:
#2
import numpy as np
import pandas as pd
x_miss = np.array([[1,2,3,None],[5,np.NaN,7,6],
                  [None,2,9,1],[5,np.NaN,3,2],[2,,None,6]])
x_m = pd.DataFrame(x_miss, columns=list('abcd'))
print(x_m)
for col in x_m.columns:
    x_m[col] = x_m[col].fillna(x_m[col].mode()[0])
print(x_m)

      a    b     c     d
0     1    2     3  None
1     5  NaN     7     6
2  None    2     9     1
3     5  NaN     3     2
4     2    6  None     6
   a  b  c  d
0  1  2  3  6
1  5  2  7  6
2  5  2  9  1
3  5  2  3  2
4  2  6  3  6


In [33]:
#3
import numpy as np
import pandas as pd
from sklearn.impute import SimpleImputer
x_miss = np.array([[1,2,3,None],[5,np.NaN,7,6],
                  [None,2,9,1],[5,np.NaN,3,2],[2,5,None,6]])
x_m = pd.DataFrame(x_miss, columns=list('abcd'))
print(x_m)
im = SimpleImputer(strategy='mean')
x_m = im.fit_transform(x_miss)
x_m = pd.DataFrame(x_m,columns=list('abcd'))
print(x_m)

      a    b     c     d
0     1    2     3  None
1     5  NaN     7     6
2  None    2     9     1
3     5  NaN     3     2
4     2    5  None     6
      a    b    c     d
0  1.00  2.0  3.0  3.75
1  5.00  3.0  7.0  6.00
2  3.25  2.0  9.0  1.00
3  5.00  3.0  3.0  2.00
4  2.00  5.0  5.5  6.00


In [34]:
#4
from collections import Counter
from sklearn.datasets import make_classification
from imblearn.over_sampling import SMOTE, ADASYN
X, y = make_classification(n_classes=4,
                           weights=[0.03,0.07,0.85,0.05], n_features=10,
                           n_clusters_per_class=1, n_samples=2000, random_state=10)
print('Original dataset shape Counter %s' % Counter(y))

Original dataset shape Counter Counter({2: 1685, 1: 145, 3: 105, 0: 65})
