In [34]:
#1
from sklearn.feature_extraction import DictVectorizer
x = [{'city' : 'Daegu','temp':12},
     {'city' : 'Seoul','temp':10},
     {'city' : 'Busan','temp':15},
     {'city' : 'Incheon','temp':9}]
vec = DictVectorizer(sparse=False)
x1 = vec.fit_transform(x)
vec = DictVectorizer(sparse=True)
x2 = vec.fit_transform(x)
print(x1)
print(x2)
print(vec.get_feature_names())

[[ 0.  1.  0.  0. 12.]
 [ 0.  0.  0.  1. 10.]
 [ 1.  0.  0.  0. 15.]
 [ 0.  0.  1.  0.  9.]]
  (0, 1)	1.0
  (0, 4)	12.0
  (1, 3)	1.0
  (1, 4)	10.0
  (2, 0)	1.0
  (2, 4)	15.0
  (3, 2)	1.0
  (3, 4)	9.0
['city=Busan', 'city=Daegu', 'city=Incheon', 'city=Seoul', 'temp']


c:\Users\user\anaconda3\lib\site-packages\sklearn\utils\deprecation.py:87: FutureWarning:

Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.



In [35]:
#2
import numpy as np
import pandas as pd
x_miss = np.array([[1,2,3,None],[5,np.NaN,7,6],
                  [None,2,9,1],[5,np.NaN,3,2],[2,6,None,6]])
x_m = pd.DataFrame(x_miss, columns=list('abcd'))
print(x_m)
for col in x_m.columns:
    x_m[col] = x_m[col].fillna(x_m[col].mode()[0])
print(x_m)

      a    b     c     d
0     1    2     3  None
1     5  NaN     7     6
2  None    2     9     1
3     5  NaN     3     2
4     2    6  None     6
   a  b  c  d
0  1  2  3  6
1  5  2  7  6
2  5  2  9  1
3  5  2  3  2
4  2  6  3  6


In [36]:
#3
import numpy as np
import pandas as pd
from sklearn.impute import SimpleImputer
x_miss = np.array([[1,2,3,None],[5,np.NaN,7,6],
                  [None,2,9,1],[5,np.NaN,3,2],[2,5,None,6]])
x_m = pd.DataFrame(x_miss, columns=list('abcd'))
print(x_m)
im = SimpleImputer(strategy='mean')
x_m = im.fit_transform(x_miss)
x_m = pd.DataFrame(x_m,columns=list('abcd'))
print(x_m)

      a    b     c     d
0     1    2     3  None
1     5  NaN     7     6
2  None    2     9     1
3     5  NaN     3     2
4     2    5  None     6
      a    b    c     d
0  1.00  2.0  3.0  3.75
1  5.00  3.0  7.0  6.00
2  3.25  2.0  9.0  1.00
3  5.00  3.0  3.0  2.00
4  2.00  5.0  5.5  6.00


In [37]:
#4
from collections import Counter
from sklearn.datasets import make_classification
from imblearn.over_sampling import SMOTE, ADASYN
X, y = make_classification(n_classes=4,
                           weights=[0.03,0.07,0.85,0.05], n_features=10,
                           n_clusters_per_class=1, n_samples=2000, random_state=10)
print('Original dataset shape %s' % Counter(y))
sm = SMOTE(random_state=42)
X_res,y_res = sm.fit_resample(X,y)
print('Resampled dataset shape from SMOTE %s' % Counter(y_res))
ada = ADASYN(random_state=0)
X_syn, y_syn = ada.fit_resample(X,y)
print('Resampled dataset shape from ADASYN %s' % Counter(y_syn))

Original dataset shape Counter({2: 1685, 1: 145, 3: 105, 0: 65})
Resampled dataset shape from SMOTE Counter({2: 1685, 1: 1685, 0: 1685, 3: 1685})
Resampled dataset shape from ADASYN Counter({1: 1703, 0: 1687, 2: 1685, 3: 1682})


In [38]:
#5
import numpy as np
y = np.array([5,3,6,1,2,4])
print(y)
y1 = y + np.array([0.1,-0.2,0.2,0.1,-0.3,-0.1])
print(y1)
MSE = np.square(np.subtract(y,y1)).mean()
print('MSE = %f' % MSE)

[5 3 6 1 2 4]
[5.1 2.8 6.2 1.1 1.7 3.9]
MSE = 0.033333


In [39]:
#6
import numpy as np
y = np.array([0,0,1,0,1,1])
p = np.array([0.1,0.2,0.9,0.1,0.8,0.7])
print(y)
print(p)
BE = -(y*np.log(p)+(1-y)*np.log(1-p)).sum()
print('BE = %f' % BE)

[0 0 1 0 1 1]
[0.1 0.2 0.9 0.1 0.8 0.7]
BE = 1.119044


In [40]:
#7
import plotly.express as px
iris_df = px.data.iris()
iris_df.head()

sepal_length  sepal_width  petal_length  petal_width species  species_id
0           5.1          3.5           1.4          0.2  setosa           1
1           4.9          3.0           1.4          0.2  setosa           1
2           4.7          3.2           1.3          0.2  setosa           1
3           4.6          3.1           1.5          0.2  setosa           1
4           5.0          3.6           1.4          0.2  setosa           1

In [42]:
#8
%matplotlib inline
feature = ['sepal_width','petal_length','petal_width']
for i in range(3):
    for j in range(i,3):
        fig = px.scatter(iris_df, x='sepal_length', y=feature[j],
                         color='species', title='Scatter Plot')
        fig.show()